ALTER TABLE users
  ADD COLUMN full_name VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN phone VARCHAR(20) NOT NULL DEFAULT '',
  ADD COLUMN gender VARCHAR(24) NOT NULL DEFAULT '';

CREATE TABLE user_wishlist (
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, product_id)
);
